#+TITLE: PREAMBLE
#+AUTHOR: Rahuketu86
#+EMAIL: rahuketu86@gmail.com
#+OPTIONS: toc:3 num:nil ^:nil



* What do I want to do?

** Focus on Writing
    I want to write more, publish more than do feature coding all the
    time. Development should be driven by workflow which is easiet and
    conducive to write more blogs than more coding on the blog. If that means
    I want to write more, publish more than code more. Development
    should be driven by workflow which is easiet and conducive to
    write more blogs than require more coding for features.
    :Note:
    If that means maintaining entire blog in single org file than fine.
    :END:
   
** Start Simple and improve progressively
    Focus on features which are required or are absolutely trivial to
    implement and maintain than which are buzzwords or so called best
    practises.

** Stay within org-mode and emacs as much as possible
    This is infact reinstating above 2 points in a way.

** Scratch the itch
    This is in a way a blog to scratch my itch about static site
    generators in general; driven by a desire to control the entire
    generators in general driven by a desire to control the entire
    possible stack.
